version: "3"
services:
  redis:
    image: redis
    ports:
      - "7379:6379"
    command: redis-server --requirepass ${REDIS_PASSWORD}
  iws: 
      build: .
      ports: 
        - 3000:3000
      environment:
        - REDIS_HOSTNAME=redis
        - REDIS_PASSWORD=${REDIS_PASSWORD}
        - COOKIE_PASSWORD=${COOKIE_PASSWORD}
        - HTTPS=${HTTPS}
      command: npm start 