version: "3"
services:
  redis:
    image: redis
    ports:
      - "7379:6379"
    command: redis-server --requirepass ${REDIS_SECRET}
  iws: 
      build: .
      ports: 
        - 3000:3000
      environment:
        - REDIS_HOST=redis
        - REDIS_SECRET=${REDIS_SECRET}
        - COOKIE_SECRET=${COOKIE_SECRET}
        - HTTPS=false
      command: npm start 